name: DailyFrame
options:
  bundleIdPrefix: com.paz
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "16.1"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: false
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  DailyFrame-iOS:
    type: application
    platform: iOS
    sources:
      - path: DailyFrame
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paz.dailyframe
        PRODUCT_NAME: DailyFrame
        INFOPLIST_FILE: DailyFrame/Info.plist
        CODE_SIGN_ENTITLEMENTS: DailyFrame/DailyFrame.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KDZZFKGF55
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"

  DailyFrame-macOS:
    type: application
    platform: macOS
    supportedDestinations: [macOS]
    sources:
      - path: DailyFrame
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paz.dailyframe.macos
        PRODUCT_NAME: DailyFrame
        INFOPLIST_FILE: DailyFrame/Info.plist
        CODE_SIGN_ENTITLEMENTS: DailyFrame/DailyFrame.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KDZZFKGF55
        MACOSX_DEPLOYMENT_TARGET: "26.0"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"

schemes:
  DailyFrame-iOS:
    build:
      targets:
        DailyFrame-iOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  DailyFrame-macOS:
    build:
      targets:
        DailyFrame-macOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
